# .github/workflows/simple-ci.yml
name: Simple CI Checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check HTML files exist
      run: |
        if [ ! -f "index.html" ]; then
          echo "❌ Error: index.html no encontrado"
          exit 1
        fi
        echo "✅ Archivos HTML encontrados"

    - name: Validate basic structure
      run: |
        # Verifica que index.html tenga la estructura básica
        if ! grep -q "<!DOCTYPE html>" index.html; then
          echo "❌ Error: Falta DOCTYPE en index.html"
          exit 1
        fi
        echo "✅ Estructura HTML válida"

    - name: Check for console errors (simulado)
      run: |
        echo "✅ Chequeo básico completado para ceoget-bootcamp-site"
